---
name: Setup forkliftci env
description: Build and setup the forkliftci env with kind
runs:
  using: composite
  steps:
    - name: Checkout forklift
      uses: actions/checkout@v3
      with:
        repository: kubev2v/forklift
        path: forklift

    - name: Bazel cache
      id: bazel-cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/bazel
        key: ${{ runner.os }}-bazel-cache-${{ hashFiles('WORKSPACE') }}

    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - name: Get kubectl
      shell: bash
      run: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && chmod u+x kubectl

    - name: Build and setup everything with bazel
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export CDI_VERSION=$(gh api repos/kubevirt/containerized-data-importer/releases/latest | jq -r ".tag_name")
        cd ${{ github.action_path }}
        FORKLIFT_DIR=$GITHUB_WORKSPACE build_and_setup_everything_bazel.sh
        cd -
