---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vcsim-certificate
  namespace: konveyor-forklift
spec:
  isCA: true
  dnsNames:
  - vcsim.konveyor-forklift
  commonName: vcsim-certificate
  secretName: vcsim-certificate
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: forklift-issuer
    kind: Issuer
    group: cert-manager.io
