---
kind: Secret
apiVersion: v1
metadata:
  name: vsphere-provider-secret
  namespace: konveyor-forklift
  labels:
    createdForResource: vsphere-provider
    createdForResourceType: providers
data:
  password: MTIzNDU2Cg==
  thumbprint: >-
    NTI6NkM6NEU6ODg6MUQ6Nzg6QUU6MTI6MUM6RjM6QkI6NkM6NUI6RjQ6RTI6ODI6ODY6QTc6MDg6QUY
  user: YWRtaW5pc3RyYXRvckB2c3BoZXJlLmxvY2Fs
type: Opaque
---
apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
metadata:
  name: vsphere-provider
  namespace: konveyor-forklift
spec:
  secret:
    name: vsphere-provider-secret
    namespace: konveyor-forklift
  settings:
    vddkInitImage: 'quay.io/kubev2v/vddk-test-vmdk'
  type: vsphere
  url: 'https://vcsim.konveyor-forklift:8989/sdk'
