---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fakeovirt
  namespace: konveyor-forklift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fakeovirt
  template:
    metadata:
      labels:
        app: fakeovirt
    spec:
      containers:
      - name: fakeovirt
        image: quay.io/kubev2v/fakeovirt:latest
        ports:
        - containerPort: 30001
        env:
          - name: NAMESPACE
            value: konveyor-forklift
          - name: PORT
            value: "30001"

---
apiVersion: v1
kind: Service
metadata:
  name: fakeovirt
  namespace: konveyor-forklift
spec:
  selector:
    app: fakeovirt
  type: NodePort
  ports:
  - name: fakeovirt
    port: 30001
    nodePort: 30001
