---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: packstack
  namespace: konveyor-forklift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: packstack
  template:
    metadata:
      labels:
        app: packstack
    spec:
      containers:
      - name: packstack
        image: quay.io/kubev2v/packstack:latest
        securityContext:        
          privileged: true
          runAsUser: 0
          capabilities:
            add:
              - ALL
        ports:
        - containerPort: 5000
        - containerPort: 8774        
        - containerPort: 8775
        - containerPort: 8778
        - containerPort: 9292
        - containerPort: 8776
        - name: neutron-port
          containerPort: 9696
        volumeMounts:
        - mountPath: /lib/modules
          name: kernel-modules
        startupProbe:
          httpGet:
            path: /
            port: 9696
          failureThreshold: 30
          periodSeconds: 10
        env:
          - name: EXTERNAL_IP
            value: <set_external_ip>
          - name: NAMESPACE
            value: konveyor-forklift
          - name: PORT
            value: "30001"
      volumes:
      - name: kernel-modules
        hostPath:
          path: /lib/modules
          # this field is optional
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: packstack
  namespace: konveyor-forklift
spec:
  selector:
    app: packstack
  type: NodePort
  ports:
  - name: keystone-api
    port: 5000
    nodePort: 30050
  - name: nova-api
    port: 8774
  - name: nova-8775
    port: 8775
  - name: placeement-api
    port: 8778
  - name: glance-api
    port: 9292    
  - name: neutron-api
    port: 9696    
  - name: cinder-api
    port: 8776
