---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-forklift
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /data/
