apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/tmp/kind_storage
        containerPath: /data
    extraPortMappings:
    - containerPort: 30001
      hostPort: 30001
featureGates:
  LegacyServiceAccountTokenNoAutoGeneration: false
